name: Build Binaries
on:
  push: { branches: ["*"] }
  workflow_dispatch: {}

jobs:
  build:
    name: Build (pkg)
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: 🔨 Build Binaries
      run: npm run build

    - name: Upload Linux binary
      uses: actions/upload-artifact@v3
      with:
        name: midi-relay-linux
        path: build/midi-relay-linux

    - name: Upload MacOS binary
      uses: actions/upload-artifact@v3
      with:
        name: midi-relay-macos
        path: build/midi-relay-macos

    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: midi-relay-win
        path: build/midi-relay-win.exe
